import { type NextPage } from "next";
import Head from "next/head";
import Hero from "~/components/Hero";
import ThumbnailPrompts from "~/components/ThumbnailPrompts";
import Titles from "~/components/Titles";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <div className="bg-[#f1f2f7]">
      <Head>
        <title>YouTube Click ChatGPT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto flex min-h-screen max-w-5xl flex-col">
        <Hero />
        <Titles />
        <ThumbnailPrompts />
      </main>
    </div>
  );
};

export default Home;
